# -*- coding: utf-8 -*-
"""healthcare.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/144kUIcEkykntMlW6r1JtFCvNhbmCQ3re
"""

from google.colab import drive
drive.mount('/content/drive')

file_path="/content/drive/MyDrive/healthcare_dataset.csv"

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv(file_path)

df.head()

print("Rows and Columns:", df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nDataset Information:")
df.info()

print(df.isnull().sum())

df['Age'] = df['Age'].fillna(df['Age'].median())
df['Billing Amount'] = df['Billing Amount'].fillna(df['Billing Amount'].median())

df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Medical Condition'] = df['Medical Condition'].fillna(df['Medical Condition'].mode()[0])
df['Admission Type'] = df['Admission Type'].fillna(df['Admission Type'].mode()[0])

df['Date of Admission'] = pd.to_datetime(
    df['Date of Admission'],
    errors='coerce'
)

df['Discharge Date'] = pd.to_datetime(
    df['Discharge Date'],
    errors='coerce'
)

print(df[['Date of Admission', 'Discharge Date']].head())

df['Hospital Stay Days'] = (
    df['Discharge Date'] - df['Date of Admission']
).dt.days

df[['Date of Admission', 'Discharge Date', 'Hospital Stay Days']].head()

df['Admission Type'] = df['Admission Type'].str.strip().str.title()

df['Urgency Category'] = df['Admission Type'].replace({
    'Emergency': 'Emergency',
    'Elective': 'Elective',
    'Urgent': 'Urgent'
})

print(df['Urgency Category'].value_counts())

print("Billing Amount Statistics")

print("Mean:", df['Billing Amount'].mean())
print("Median:", df['Billing Amount'].median())
print("Minimum:", df['Billing Amount'].min())
print("Maximum:", df['Billing Amount'].max())
print("Standard Deviation:", df['Billing Amount'].std())

print("Hospital Stay Statistics")

print("Mean:", df['Hospital Stay Days'].mean())
print("Median:", df['Hospital Stay Days'].median())
print("Minimum:", df['Hospital Stay Days'].min())
print("Maximum:", df['Hospital Stay Days'].max())
print("Standard Deviation:", df['Hospital Stay Days'].std())

df[['Billing Amount', 'Hospital Stay Days']].describe()

print(df['Medical Condition'].value_counts())

demographic_analysis = df.groupby('Medical Condition').agg(
    Average_Age=('Age', 'mean'),
    Patient_Count=('Age', 'count')
)

print(demographic_analysis)

gender_condition = pd.crosstab(
    df['Medical Condition'],
    df['Gender']
)

print(gender_condition)

condition_billing = df.groupby('Medical Condition')['Billing Amount'].mean()
print(condition_billing)

condition_stay = df.groupby('Medical Condition')['Hospital Stay Days'].mean()
print(condition_stay)

"""**Simple Visualization**"""

import matplotlib.pyplot as plt
df['Medical Condition'].value_counts().plot(kind='bar')
plt.title('Patients by Medical Condition')
plt.xlabel('Medical Condition')
plt.ylabel('Number of Patients')
plt.xticks(rotation=45)
plt.show()

"""**Billing Amount Distribution**"""

plt.hist(df['Billing Amount'], bins=20)
plt.title('Billing Amount Distribution')
plt.xlabel('Billing Amount')
plt.ylabel('Number of Patients')
plt.show()

"""**Hospital Stay Distribution**"""

plt.hist(df['Hospital Stay Days'], bins=15)
plt.title('Hospital Stay Distribution')
plt.xlabel('Hospital Stay Days')
plt.ylabel('Number of Patients')
plt.show()

print(df.isnull().sum())

df.head()

